---
analyze_property_task:
  description: Analyze the Property CSV located at {property_csv_path} for the listing
    with ID {listing_id}. Extract the location data such as {City} and {State} and
    use WebsiteSearchTool to perform web searches with queries like 'housing crisis
    in {City} {State}', 'affordable housing {City} {State} 2025' and 'attainable housing
    solutions {City} {State}'. Synthesize the results into a summary report evaluating
    local housing market sentiment and the potential for attainable housing.
  expected_output: A detailed summary report for the listing in {City}, {State} that
    includes market sentiment on housing/rent affordability and prospects for attainable
    housing based on web research and CSV data.
  async_execution: false
  agent: property_analyst
analyze_environmental_task:
  description: Examine the Environmental CSV located at {environmental_csv_path} for
    the listing with ID {listing_id}. Evaluate data points (In SFHA, FEMA Flood Zone,
    FEMA Map Date, Floodplain Area) to assess environmental hazards such as flood
    risk. Use the WebsiteSearchTool to better understand what the various data points
    mean.
  expected_output: A comprehensive environmental risk analysis detailing hazard levels
    and potential environmental challenges for the property.
  async_execution: false
  agent: environmental_evaluator
analyze_growth_trends_task:
  description: Evaluate the Growth Trends CSV located at {growth_trends_csv_path}
    for the listing with ID {listing_id}. Extract population growth percentages for
    both 5-mile and 10-mile radii (e.g., % Pop Growth 2020-2024, % Pop Growth 2024-2029)
    to assess historical and projected market expansion between these regions. In
    addition use the WebsiteSearchTool to query things like 'economic growth in {City}
    {State} 2025' and 'job growth in the {City} {State} region'.
  expected_output: An in-depth analysis report of growth trends, including key metrics
    that indicate potential market expansion opportunities.
  async_execution: false
  agent: growth_trends_expert
analyze_housing_occupancy_task:
  description: Analyze the Housing Units and Occupancy CSV located at {occupancy_csv_path}
    for the listing with ID {listing_id}. Investigate metrics such as TotHUs_5, OccHUs_5,
    VacHUs_5, and corresponding 10-mile metrics to determine the occupancy and vacancy
    profiles. Identify trends that might affect property usage and development potential.
  expected_output: A detailed report on current housing occupancy trends, including
    quantified metrics on vacancies and unit usage patterns.
  async_execution: false
  agent: occupancy_expert
analyze_demographics_affordability_task:
  description: Assess the Demographics and Affordability CSV located at {demographics_csv_path}
    for the listing with ID {listing_id}. Analyze community profile data (TotPop,
    age distributions, TotHHs) alongside affordability data (housing value ranges,
    MedianHValue, MedianGrossRent, MedianHHInc). Incorporate external web research
    using WebsiteSearchTool if necessary, with queries such as 'housing affordability
    trends {City} 2025' to evaluate local economic pressures.
  expected_output: A comprehensive socio-economic and affordability analysis report
    that outlines the key demographics and affordability pressures relevant to property
    development.
  async_execution: false
  agent: socio_economic_analyst
integrate_analysis_task:
  description: Aggregate and correlate outputs from the 'analyze_property_task', 'analyze_environmental_task',
    'analyze_growth_trends_task', 'analyze_housing_occupancy_task', and 'analyze_demographics_affordability_task'.
    Evaluate overall risk and opportunity levels for the property with ID {listing_id}.
    Develop strategic recommendations that balance market potential with identified
    risks.
  expected_output: An integrated evaluation report section that provides a unified
    risk and opportunity assessment with clear strategic recommendations for the property.
  async_execution: false
  agent: integrated_evaluator
  context:
  - analyze_property_task
  - analyze_environmental_task
  - analyze_growth_trends_task
  - analyze_housing_occupancy_task
  - analyze_demographics_affordability_task
compile_narrative_report_task:
  description: Compile a final high-quality narrative report in a professional land
    analyst style that integrates the findings from the integrated evaluation. The
    report should include an executive summary, detailed sections on Property Analysis,
    Environmental Risk, Growth Trends, Housing Occupancy, Socio-economic Factors,
    and a concluding recommendations section. Ensure the report is polished and easily
    digestible for decision-making purposes.
  expected_output: A final comprehensive narrative report that consolidates all analytical
    findings into an executive-level document with data insights, expert commentary,
    and actionable recommendations.
  async_execution: false
  agent: narrative_reporter
  context:
  - integrate_analysis_task
