---
analyze_property_task:
  description: Analyze the Property CSV located at {property_csv_path} for the listing
    with ID {listing_id}. Extract the location data such as {City} and {State} and
    use WebsiteSearchTool to perform web searches with queries like 'housing crisis
    in {City} {State}', 'affordable housing {City} {State} 2025' and 'attainable housing
    solutions {City} {State}'. Synthesize the results into a summary report evaluating
    local housing market sentiment and the potential for attainable housing.
  expected_output: A detailed summary report for the listing in {City}, {State} that
    includes market sentiment on housing/rent affordability and prospects for attainable
    housing based on web research and CSV data.
  async_execution: false
  agent: property_analyst
analyze_environmental_task:
  description: Examine the Environmental CSV located at {environmental_csv_path} for
    the listing with ID {listing_id}. Evaluate data points (In SFHA, FEMA Flood Zone,
    FEMA Map Date, Floodplain Area) to assess environmental hazards such as flood
    risk. Use the WebsiteSearchTool to better understand what the various data points
    mean.
  expected_output: A comprehensive environmental risk analysis detailing hazard levels
    and potential environmental challenges for the property.
  async_execution: false
  agent: environmental_evaluator
analyze_growth_trends_task:
  description: Evaluate the Growth Trends CSV located at {growth_trends_csv_path}
    for the listing with ID {listing_id}. Extract population growth percentages for
    both 5-mile and 10-mile radii (e.g., % Pop Growth 2020-2024, % Pop Growth 2024-2029)
    to assess historical and projected market expansion between these regions. Conduct 
    extensive web research using WebsiteSearchTool for specific companies investing
    in {City} {State} with queries such as 'companies expanding in {City} {State}',
    'new factories in {City} {State} 2025', 'corporate headquarters moving to {City} {State}',
    'economic development plans {City} {State}', 'major construction projects {City} {State}',
    'job creation {City} {State}', etc. For each company or development project found, research
    and include specific details: company name, industry, planned investment amount, 
    number of jobs expected, construction/opening timeline, and impact on the local economy.
    Also research local government economic development plans and incentives that could
    attract additional businesses to the area.
  expected_output: A comprehensive analysis of growth trends that includes both demographic
    projections AND specific details about companies investing in the region. Your report
    should name individual companies, their expansion plans, job creation numbers, investment
    amounts, timelines, and economic impacts. Include information on government economic
    development initiatives. This detailed information should be sufficient to allow clients
    to conduct their own follow-up research on the specific companies and projects mentioned.
  async_execution: false
  agent: growth_trends_expert
analyze_housing_occupancy_task:
  description: Analyze the Housing Units and Occupancy CSV located at {occupancy_csv_path}
    for the listing with ID {listing_id}. Investigate metrics such as TotHUs_5, OccHUs_5,
    VacHUs_5, and corresponding 10-mile metrics to determine the occupancy and vacancy
    profiles. Identify trends that might affect property usage and development potential.
    Evaluate whether the market appears to be oversaturated with similar developments 
    or if there is still room for growth.
  expected_output: A detailed report on current housing occupancy trends, including
    quantified metrics on vacancies and unit usage patterns, as well as analysis of 
    market saturation for similar developments.
  async_execution: false
  agent: occupancy_expert
analyze_demographics_affordability_task:
  description: Assess the Demographics and Affordability CSV located at {demographics_csv_path}
    for the listing with ID {listing_id}. Analyze community profile data (TotPop,
    age distributions, TotHHs) alongside affordability data (housing value ranges,
    MedianHValue, MedianGrossRent, MedianHHInc). Incorporate external web research
    using WebsiteSearchTool if necessary, with queries such as 'housing affordability
    trends {City} 2025' to evaluate local economic pressures.
  expected_output: A comprehensive socio-economic and affordability analysis report
    that outlines the key demographics and affordability pressures relevant to property
    development.
  async_execution: false
  agent: socio_economic_analyst
integrate_analysis_task:
  description: Aggregate and correlate outputs from the 'analyze_property_task', 'analyze_environmental_task',
    'analyze_growth_trends_task', 'analyze_housing_occupancy_task', and 'analyze_demographics_affordability_task'.
    Evaluate overall risk and opportunity levels for the property with ID {listing_id}.
    Develop strategic recommendations that balance market potential with identified
    risks. Do not summarize or condense the detailed information - especially from the 
    growth trends analysis. Maintain all company names, economic development plans, and 
    specific details in your integrated report.
  expected_output: An integrated evaluation report section that provides a unified
    risk and opportunity assessment with clear strategic recommendations for the property.
    This integration should preserve ALL detailed information from the individual analyses,
    particularly the specific company names and development plans from the growth trends analysis.
  async_execution: false
  agent: integrated_evaluator
  context:
  - analyze_property_task
  - analyze_environmental_task
  - analyze_growth_trends_task
  - analyze_housing_occupancy_task
  - analyze_demographics_affordability_task
compile_narrative_report_task:
  description: Compile a final comprehensive narrative report in a professional land
    analyst style that integrates the findings from the integrated evaluation. The
    report should include an executive summary and detailed sections on Property Analysis,
    Environmental Risk, Growth Trends, Housing Occupancy, Socio-economic Factors,
    and a concluding recommendations section. The Growth Trends section should be particularly
    detailed, including specific company names, investment plans, job creation numbers, 
    timelines, and economic development initiatives. Do not summarize or condense information
    to keep the report short - include ALL details that would be valuable for further research.
    The report should be as long as necessary to convey all findings in full detail.
  expected_output: A comprehensive, thorough narrative report that includes ALL analytical
    findings with complete details. The report should be a research tool that provides
    actionable intelligence, including specific company names, economic development plans,
    timelines, and investment details. The report should be as long as needed to include
    all relevant information without summarizing or condensing important details.
  async_execution: false
  agent: narrative_reporter
  context:
  - integrate_analysis_task
